sudo: false
matrix:
  fast_finish: true
  include:
  - python: '3.5'
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: 'nightly'
    env: TOXENV=py37
  - python: '3.7-dev'
    env: TOXENV=py37
  - python: '3.8-dev'
    env: TOXENV=py38

  - python: '3.5'
    env: TOXENV=lint

  allow_failures:
  - python: 'nightly'
  - python: '3.8-dev'

cache:
  directories:
  - "$HOME/.cache/pip"
install:
- pip install aiohttp async_timeout
script:
- flake8 mill --max-line-length=120
- pylint mill --max-line-length=120
