sudo: false
matrix:
  fast_finish: true
  include:
  - python: '3.5'
    env: TOXENV=lint
cache:
  directories:
  - "$HOME/.cache/pip"
install:
- pip install flake8 pylint aiohttp async_timeout
language: python
script:
- flake8 mill --max-line-length=120
- pylint mill --max-line-length=120
deploy:
  password:
    secure: nMneewwc/DhKZH8caBuuAQTorGOgKHfzVgKdfb6oJia0PNbS6AvwXwFEpaF3BttQSuyb9jfdNrJBtWUTBniE5RjDlMbXbV2FAzjfVIRmHvjSi2mGkhoxVhH7+y7ymZhVwuwFupRLhTFiORrWvxaEP4ScA//bPnGjvgklIwV8THq4FNI75LQtU3S69pm/4JbSqK5vOR32oUU5bHqiWJvenm0z5af3ujN44+MHhX4A4SjO3IhgNO7PJp6bYMHmzltHiauh+271hzICKNwycDPXkSL6mTad/QgQTb+4jDuN4I2Dh76ym3N5si7eOxSRcurYrEx5iOk5bANZ97P2cVA7D9Ie+x3SIuk8xDqvl7GpHWz1kk5vpQuFpYsi0ZP3SE4XvCvyoLIs+FW1xT3u+HkSoimgeuOPLJrUPGaak091j0uW/natWv//FZDeK0ANkTgNRZ0mAbRvOfgU4NjfARHdLMKd1xmFFVP9E7B0HVkOIWKpWpEpXPpI9tOsE+OcFTMlzaG1CVOzIic9rgqXjlYJmaSOLvt9/zU7sI8tAF3FCBEvW6ptbP71lwY2OpAC1s3y8HvqmV989qVeFlbXGVga8LN3upA6jwqIZfGTpAPlvJuDfU4XNQGmjA1gV5WFGGBb+yNG8UMYS/H7ZFA5SJcbd+cL8cp/AkIDNQQIpcfN4QE=
  on:
    tags: true
    repo: Danielhiversen/pymill
    branch: master
