sudo: false
matrix:
  fast_finish: true
  include:
  - python: '3.5'
    env: TOXENV=lint
cache:
  directories:
  - "$HOME/.cache/pip"
install:
- pip install flake8 pylint aiohttp async_timeout cryptography
language: python
script:
- flake8 mill --max-line-length=120
- pylint mill --max-line-length=120
